### ISSUE TITLE
Deploy new db dump along with new extension 1.0.0

### ISSUE THREAD

**Issue by rafatower** [CartoDB/observatory-extension#129]
* Dump ID: `2016_06_28_38328f72b7`
* Extension version: `1.0.0`

Procedure:
- [x] deploy in staging (production blue/green), setting up a few users to point to it (@iriberri rafatower and @talos at least)
- [x] run regression tests we have to date.
- [x] manual test it
- [ ] promote to production.

**Comment by rafatower** [comment]
@talos just an update: I'm deploying the new dump right now. We'll get the benefits of the latest indices patch. It'll take a while though... Cheers!

**Comment by talos** [comment]
✨ Thank you!

**Comment by rafatower** [comment]
Executing the end-to-end [integration tests](https://github.com/CartoDB/dataservices-api/tree/development/test), I'm getting this error:

```
ERROR: test_if_obs_get_available_boundaries_is_ok (test.integration.test_data_observatory_functions.TestDataObservatoryFunctions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rtorre/src/dataservices-api/test/integration/test_data_observatory_functions.py", line 148, in test_if_obs_get_available_boundaries_is_ok
    result = IntegrationTestHelper.execute_query(self.sql_api_url, query)
  File "/home/rtorre/src/dataservices-api/test/helpers/integration_test_helper.py", line 29, in execute_query
    raise Exception(json.loads(query_response.text)['error'])
Exception: [u'cdb_dataservices_client._obs_getavailableboundaries(4): [cartodb_user_a6f0d0fe-4f4f-4217-8150-22b0010fe409_db] REMOTE ERROR: plpy.Error: There was an error trying to use OBS_GetAvailableBoundaries: cdb_dataservices_server._obs_getavailableboundaries(4): [obs_2016_06_28_38328f72b7] REMOTE ERROR: Operation on mixed SRID geometries']
-------------------- >> begin captured stdout << ---------------------
Executing query: https://rtorre.cartodb.com/api/v1/sql?q=SELECT boundary_id FROM OBS_GetAvailableBoundaries(CDB_LatLng(40.704512, -73.936669)) LIMIT 1;&api_key=[omitted]

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTPS connection (1): rtorre.cartodb.com
requests.packages.urllib3.connectionpool: DEBUG: "GET /api/v1/sql?q=SELECT%20boundary_id%20FROM%20OBS_GetAvailableBoundaries(CDB_LatLng(40.704512,%20-73.936669))%20LIMIT%201;&api_key=[omitted] HTTP/1.1" 400 344
--------------------- >> end captured logging << ---------------------
```

(the important bit I guess it's `REMOTE ERROR: Operation on mixed SRID geometries'`)

What worries me a little is that that suite is pretty basic and does not cover everything.

**Comment by talos** [comment]
This looks like the same error we were seeing before in a different guise.

While those tests aren't complete, when combined with the integration tests in observatory-extension (which cover every possible getmeasure and getcategory call) we do have pretty good coverage.

I think a good, and relatively easy improvement, would be to run your the `dataservices-api` integration tests before going forward with a deploy process.  I'll do that now.

**Comment by talos** [comment]
I'm not able to reproduce this error in the test environment, but on staging (jkrauss.cartodb.com) I can get the function to work with ST_Point (no SRID) but not with CDB_LatLng (has an SRID). 

This makes me think that the SRID is getting dropped somehow in the dump.

Wrapper function without SRID set: https://github.com/CartoDB/dataservices-api/blob/27124e26dd6689fccd25afab4d33667e091d89f8/client/cdb_dataservices_client--0.7.0.sql#L967

Internal function with SRID set: https://github.com/CartoDB/observatory-extension/blob/develop/src/pg/sql/42_observatory_exploration.sql#L87

Would it be possible to log into the staging server and check the `st_srid` of `the_geom` in `obs_table` on not-null `the_geom`s?

Two probable solutions:

1. Preemptively `set_srid` on `the_geom` before `st_intersection`: https://github.com/CartoDB/observatory-extension/pull/130
2. Define an SRID of 4326 for `the_geom` in `obs_table` (which will necessitate another dump).

**Comment by talos** [comment]
@rafatower ^^^

**Comment by rafatower** [comment]
I just tested directly on the staging server:
```
obs_2016_06_28_38328f72b7=# SELECT boundary_id FROM cdb_observatory.OBS_GetAvailableBoundaries(ST_SetSRID(ST_MakePoint(40.704512, -73.936669),4326)) LIMIT 1;
ERROR:  Operation on mixed SRID geometries
CONTEXT:  PL/pgSQL function cdb_observatory.obs_getavailableboundaries(geometry,text) line 11 at RETURN QUERY
```

So I'm going for option 1. #130. Setting up and testing straight in staging

**Comment by rafatower** [comment]
Much better now:
```
obs_2016_06_28_38328f72b7=# SELECT boundary_id FROM cdb_observatory.OBS_GetAvailableBoundaries(ST_SetSRID(ST_MakePoint(40.704512, -73.936669),4326)) LIMIT 1;
          boundary_id           
--------------------------------
 whosonfirst.wof_continent_geom
(1 row)
```

**Comment by rafatower** [comment]
```
$ python run_tests.py  rtorre [my_api_key]
............................................................
----------------------------------------------------------------------
Ran 60 tests in 40.939s

OK
```
vamoosss!!!

**Comment by talos** [comment]
```
$  observatory-extension (preemptive-setsrid) ./runtest.sh
.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 1591 tests in 1658.519s

OK
```

Let's do this @rafatower  👍

**Comment by rafatower** [comment]
Hey. I released 1.0.1 and deployed it to the staging server. The only thing left from my side would be promoting it to production from staging.

As we're pretty close to the weekend but you still have some ours in your TZ I'd say please take advantage to test it as much as you want and if everything goes fine and you give me the green lights I can promote it to production.

**Comment by rafatower** [comment]
https://github.com/CartoDB/observatory-extension/releases

**Comment by talos** [comment]
I'm going to run some tests on it now and let you know how it looks.

**Comment by talos** [comment]
```
$  observatory-extension (preemptive-setsrid) ./runtest.sh
.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 1591 tests in 287.347s

OK
```

So automated tests say 👍 .  I'll do a few manual checks, but my guess is this is a-go.

**Comment by rafatower** [comment]
Following instructions: v1.0.1 is released and deployed to production. :sparkles: 

thank you, @talos
